# Generated by Django 4.0.5 on 2022-06-25 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre y apellidos del director', max_length=60)),
                ('pais', models.CharField(help_text='País de origen', max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_fallecimiento', models.DateField(blank=True, null=True)),
                ('biografia', models.TextField()),
                ('imagen', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('pais', models.CharField(help_text='País de producción', max_length=30)),
                ('resumen', models.TextField(help_text='Sinopsis de la película', max_length='255')),
                ('duracion', models.PositiveIntegerField()),
                ('agno', models.PositiveIntegerField()),
                ('genero', models.CharField(blank=True, choices=[('ACC', 'Acción'), ('ANI', 'Animación'), ('BIO', 'Biografía'), ('BEL', 'Bélico'), ('CFI', 'Ciencia Ficción'), ('COM', 'Comedia'), ('DES', 'Desastres'), ('DIS', 'Distopía'), ('DOC', 'Documental'), ('DRA', 'Drama'), ('ESP', 'Espías'), ('FAN', 'Fantasía'), ('HIS', 'Historia'), ('LEG', 'Legal'), ('MAF', 'Mafia'), ('MUS', 'Musical'), ('TER', 'Terror'), ('MIS', 'Misterio'), ('PEN', 'Penitenciario'), ('POL', 'Policíaco'), ('ROM', 'Romántico'), ('SUS', 'Suspense'), ('WES', 'Western')], help_text='Género/s cinematográficos', max_length=3)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmografia.director')),
            ],
        ),
    ]
