# Generated by Django 4.0.5 on 2022-06-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmografia', '0002_remove_director_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.PositiveIntegerField(help_text='Duración de la película en minutos'),
        ),
    ]
